### ISSUE TITLE
为什么不直接把 Message 类暴露出去，这样可以存在多种配置的实例。

### ISSUE THREAD

**Issue by daGaiGuanYu** [nihaojob/popular-message#1]
从阮一峰老师的周刊来的，学习了，感谢  
如果言语不适当，请谅解

**Comment by nihaojob** [comment]
> 从阮一峰老师的周刊来的，学习了，感谢
> 如果言语不适当，请谅解

之前没考虑到这点，不知道这种场景不多，目前只是自己使用，后期可以一起完善，感谢建议哈。
