### ISSUE TITLE
添加单例模式的支持

### ISSUE THREAD

**Issue by LanjianNUll** [nihaojob/popular-message#4]
添加单例模式的支持

**Comment by nihaojob** [comment]
> 添加单例模式的支持

感谢 这个好，我回家格式化下代码 ，处理下pull requests.

**Comment by nihaojob** [comment]
我把代码合并上去了，gulp打包部分做了一下修改 非常感谢，但是贡献者名称没加上您的名字，是因为我选择 mrege的防止导致的吗？

如果可以的话，还请您帮忙指导一下如操作才能加上您的名字。

**Comment by LanjianNUll** [comment]
> 我把代码合并上去了，gulp打包部分做了一下修改 非常感谢，但是贡献者名称没加上您的名字，是因为我选择 mrege的防止导致的吗？
> 
> 如果可以的话，还请您帮忙指导一下如操作才能加上您的名字。

哈哈， 我也不知道怎么回事！ 不过，没关系

**Comment by nihaojob** [comment]
> > 我把代码合并上去了，gulp打包部分做了一下修改 非常感谢，但是贡献者名称没加上您的名字，是因为我选择 mrege的防止导致的吗？
> > 如果可以的话，还请您帮忙指导一下如操作才能加上您的名字。
> 
> 哈哈， 我也不知道怎么回事！ 不过，没关系

感谢哈  单例模式感觉特别棒👍🏻。
