### ISSUE TITLE
消息提示被 element-plus dialog  遮挡

### ISSUE THREAD

**Issue by shiyutim** [nihaojob/popular-message#7]
el-dialog 的 z-index 为 2000+，而 popular-message 的 z-index 为 1000+，所以需要更高的优先级

**Comment by nihaojob** [comment]
> el-dialog 的 z-index 为 2000+，而 popular-message 的 z-index 为 1000+，所以需要更高的优先级

收到，已记录这个问题，可先给  popular-message 的容器增加较高层级使用，近期修复

```
.popular-message {
z-index:4000;
}

```

**Comment by nihaojob** [comment]
> el-dialog 的 z-index 为 2000+，而 popular-message 的 z-index 为 1000+，所以需要更高的优先级


已经发布了 [v1.1.7-beta](https://github.com/nihaojob/popular-message/releases/tag/v1.1.7-beta)，在这个版本中修改了z-index的层级，感谢反馈哈。
